bonus du bonus du bonus du bonus

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -7,6 +7,8 @@ on:
       - main
   # L'action se déclenche lors d'une pull request
   pull_request:
+    branches:
+      - main
 
 jobs:
   test-backend:
@@ -29,6 +31,7 @@ jobs:
       - name: Build and test with Maven
         # On se place dans le dossier où se trouve le pom.xml et on lance mvn clean verify
         run: |
+          set -e
           cd Docker/TP1/API/simple-api-student-main
           mvn clean verify
 
@@ -52,13 +55,14 @@ jobs:
       - name: Build and test with Maven
         # On se place dans le dossier où se trouve le pom.xml et on lance l'analyse sonar
         run: |
+          set -e
           cd Docker/TP1/API/simple-api-student-main
           mvn -B verify sonar:sonar -Dsonar.projectKey=Korglos_DevOpsS8 -Dsonar.organization=korglos -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
 
 
   # Define job to build and publish Docker images
   build-and-push-docker-image:
-    needs: test-backend
+    needs: [test-backend, sonar-backend]
 
     # Run only when code is compiling and tests are passing
     runs-on: ubuntu-22.04
@@ -71,13 +75,17 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
+      - name: Define Docker Image Version
+        id: versioning
+        run: echo "VERSION=1.0.${{ github.run_number }}" >> $GITHUB_ENV
+
       - name: Build image and push backend
         uses: docker/build-push-action@v6
         with:
           # Relative path to the place where source code with Dockerfile is located
           context: ./Docker/TP1/API/simple-api-student-main
           # Note: tags have to be all lowercase
-          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
+          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:${{ env.VERSION }}
           push: ${{ github.ref == 'refs/heads/main' }}
 
       - name: Build image and push database
@@ -86,7 +94,7 @@ jobs:
           # Relative path to the place where source code with Dockerfile is located
           context: ./Docker/TP1/DataBase
           # Note: tags have to be all lowercase
-          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
+          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:${{ env.VERSION }}
           push: ${{ github.ref == 'refs/heads/main' }}
 
       - name: Build image and push httpd
@@ -95,5 +103,22 @@ jobs:
           # Relative path to the place where source code with Dockerfile is located
           context: ./Docker/TP1/Front
           # Note: tags have to be all lowercase
-          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
+          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:${{ env.VERSION }}
           push: ${{ github.ref == 'refs/heads/main' }}
+
+  cancel-pr-on-failure:
+    needs: [test-backend, sonar-backend]
+    if: failure()
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Close PR on Failure
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          pr_number=$(jq --raw-output .pull_request.number < "$GITHUB_EVENT_PATH")
+          echo "Closing PR #$pr_number due to pipeline failure"
+          curl -X PATCH \
+            -H "Authorization: token $GITHUB_TOKEN" \
+            -H "Accept: application/vnd.github.v3+json" \
+            https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number \
+            -d '{"state":"closed"}'
